spring:
  data:
    mongo:
      uri: mongodb://admin:pass@localhost:27017/leetcode
      database: leetcode
      options:
        createDatabase: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
